baseurl = "https://alexspeedfire.github.io"
title = "Рандомные куски кода."
theme="material-design"
languageCode = "en-RU"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
disqusShortname = "" # optional
copyright = "© 2019 Alex Speedfire"

[params]
  description = "Найденные в закрытом периметре" # optional
  twitter = "as_p" # optional
  gitlab = "" # optional
  github = "alexspeedfire" # optional
  facebook = "" # optional
  gplus = "" # optional
  linkedin = "" # optional
  #headerCover = "images/headerCover.png" # optional
  #footerCover = "images/footerCover.png" # optional
  googleAnalyticsUserID = "" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional